<?php

namespace Omnipay\BinancePay\Message;

use Omnipay\Common\Message\AbstractResponse;

/**
 * Class CompletePurchaseResponse
 *
 * @package Omnipay\BinancePay\Message
 */
class CompletePurchaseResponse extends AbstractResponse
{
    const PAID = 'PAID';
    const CANCELED = 'CANCELED';
    const EXPIRED = 'EXPIRED';
    const PENDING = 'PENDING';

    /**
     * Indicates whether transaction was successful
     *
     * @return bool
     */
    public function isSuccessful()
    {
        return array_get($this->data, 'data.status') === static::PAID;
    }

    public function isPending()
    {
        return array_get($this->data, 'data.status') === static::PENDING;
    }

    public function isCancelled()
    {
        return in_array(array_get($this->data, 'data.status'), [static::EXPIRED, static::CANCELED]);
    }

    /**
     * Get transaction ID, generated by merchant
     *
     * @return mixed|string
     */
    public function getTransactionId()
    {
        return array_get($this->data, 'data.prepayId');
    }

    /**
     * Get transaction reference, generated by gateway
     *
     * @return mixed|null|string
     */
    public function getTransactionReference()
    {
        return array_get($this->data, 'data.transactionId');
    }

    public function getMessage()
    {
        return json_encode($this->getData());
    }
}